version: "3.9"

services:
  financial-freedom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-freedom
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}       # generate with `php artisan key:generate --show`
      APP_DEBUG: "false"
      APP_URL: https://finance.prochat.tools
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - storage:/app/storage
      - uploads:/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financial-freedom.rule=Host(`finance.prochat.tools`)"
      - "traefik.http.routers.financial-freedom.entrypoints=web"
      - "traefik.http.routers.financial-freedom-secure.rule=Host(`finance.prochat.tools`)"
      - "traefik.http.routers.financial-freedom-secure.entrypoints=websecure"
      - "traefik.http.routers.financial-freedom-secure.tls.certresolver=letsencrypt"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: financial-freedom-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  storage:
  uploads:
  db-data:
