version: "3.8"

services:
  financialfreedom:
    image: finance-financialfreedom-x7vpmh:latest
    restart: always
    env_file:
      - .env
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - "8081:80" # expose internal port 80 → host 8081 (Traefik will route)
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    networks:
      - dokploy

networks:
  dokploy:
    external: true
